# Generated by Django 5.0.6 on 2024-07-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('documentNumber', models.CharField(max_length=255)),
                ('documentDate', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('UrAddress', models.TextField(blank=True)),
                ('ogrn', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(blank=True, max_length=255)),
                ('kpp', models.CharField(blank=True, max_length=255)),
                ('bank', models.CharField(blank=True, max_length=255)),
                ('bik', models.CharField(blank=True, max_length=255)),
                ('rs', models.CharField(blank=True, max_length=255)),
                ('ks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
