# Generated by Django 5.0.6 on 2024-07-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='UrAddress',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='bik',
            field=models.CharField(blank=True, max_length=255, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='documentDate',
            field=models.CharField(max_length=255, verbose_name='Дата договора'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='documentNumber',
            field=models.CharField(max_length=255, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='inn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='kpp',
            field=models.CharField(blank=True, max_length=255, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='ks',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кор. счет'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='ogrn',
            field=models.CharField(blank=True, max_length=255, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='rs',
            field=models.CharField(blank=True, max_length=255, verbose_name='Расчетный счет'),
        ),
    ]
